require_relative '../lib/calculate_sum'
require_relative '../lib/is_palindrome'
require_relative '../lib/reverse_integer'
require_relative '../lib/swap_node_pairs'
require_relative '../lib/counting_sort'
require_relative '../lib/quick_sort'
require_relative '../lib/string_to_i'
require_relative '../lib/median'