require_relative '../lib/calculate_sum'
require_relative '../lib/is_palindrome'
require_relative '../lib/reverse_integer'
require_relative '../lib/swap_node_pairs'
require_relative '../lib/count_sort'
require_relative '../lib/quick_sort'
require_relative '../lib/string_to_i'
require_relative '../lib/median'
require_relative '../lib/node_manipulation.rb'
require_relative '../lib/print_unordered_pairs.rb'
require_relative '../lib/merge_sort'
require_relative '../lib/07_1_cci_deck_of_cards.rb'
require_relative '../lib/parenthesis_matcher.rb'
# require_relative '../lib/javascripts/test_javascript.js'